### ISSUE TITLE
Not displaying tree and graph view

### ISSUE THREAD

**Issue by ainagaya** [BSC-ES/autosubmit-gui#194]
Hi @LuiggiTenorioK !

I'm having issues with the GUI in the experiment a1xo from the Climate DT VM.

Razvan (can't find him here) had de same issue, the experiment is not displaying the tree or the graph view.

![image](https://github.com/user-attachments/assets/9f791ac7-42fd-482c-818f-88548abe45a4)

Can you take a look? If it's more api-related feel free to move it there. Thanks!

**Comment by LuiggiTenorioK** [comment]
Hi @ainagaya

This issue is related to the version of the `autosubmitconfigparser` we have in the VM. I tried it with version 1.0.73 and it works fine. @Nortamo please confirm with us when this version of the parser is deployed to check if the problem persists.

CC @dbeltrankyl

**Comment by LuiggiTenorioK** [comment]
CC @raguridan-bsc

**Comment by Nortamo** [comment]
Updated:
```
# podman exec <containerid> pip freeze 2>/dev/null | grep autosubmitconfig
autosubmitconfigparser==1.0.73
# curl localhost:<port>
{"name":"Autosubmit API","version":"4.0.1b4"}
```

**Comment by LuiggiTenorioK** [comment]
Thank you @Nortamo! Now it works :tada:

**Comment by LuiggiTenorioK** [comment]
@ainagaya, it seems that this issue is already solved after the update since the tree view (https://climatedt-wf.csc.fi/experiment/a1xo/tree) is visible. Closing this issue.
